### ISSUE TITLE
setLibLoadingListener has no effect

### ISSUE THREAD

**Issue by solsson** [Yolean/quarkus-javet#1]
I think I've tried every build and runtime hook Quarkus has to offer, to run code that [disables](https://www.caoccao.com/Javet/reference/resource_management/load_and_unload.html#can-javet-native-library-deployment-be-skipped) built-in lib loading. In the [configure-static-tmp](https://github.com/Yolean/quarkus-javet/tree/configure-static-tmp) branch I've also tried overriding the folder to static `/tmp`.

As the current [readme](https://github.com/Yolean/quarkus-javet/blob/d6466f7288ac5b51c3d3ef73da07575b4ace9a5b/README.md) documents it's clear that attempts to load from `/tmp/javet/nn/` happen both during native-image build and at runtime. That's actually where I ended up with https://github.com/Yolean/javet-quarkus/ as well. Using an extension is a more promising approach though.

This might just be a stupid mistake somewhere, or it might be that the static `JavetLibLoader.setLibLoadingListener` is unfit for build time configuration.

**Comment by caoccao** [comment]
I think environment variables could be the solution. I'll enhance Javet to take environment variables. Please let me know if that makes sense.
